#' Read tibble from csv file.
#'
#' @description We expect the csv file is in the format generated by [DataEditR::data_edit()]:
#'   * First column is row numbers.
#'   * Date columns are chr.
#'   * Valor is chr because of comma decimal mark; must be read with locale.
#'
#' @param filename Csv file to be read, with path.
#' @return A tibble.
#' @author fnaufel
#' @importFrom readr read_csv locale
read_df <- function (filename) {

  readr::read_csv(
    filename,
    col_types = 'iDcdccciiD',
    col_select = -1,
    locale = readr::locale(decimal_mark = ',')
  )

}
