#' Write tibble to csv file.
#'
#' @description The csv file is in the format generated by [DataEditR::data_edit()]:
#'   * First column is row numbers.
#'   * Date columns are chr.
#'   * Valor is chr because of comma decimal mark; must be read with locale.
#'
#' @param df Tibble to write.
#' @param filename Csv file to write, with path.
#' @return A tibble.
#' @author fnaufel
#' @importFrom dplyr mutate select
#' @importFrom readr write_csv
write_df <- function (df, filename) {

  row_nos <- 1:nrow(df)

  df_to_write <- df %>%
    dplyr::mutate(
      n = row_nos,
      data = format(data, '%Y-%m-%d'),
      valor = str_trim(format(valor, decimal.mark = ',')),
      data_fatura = format(data_fatura, '%Y-%m-%d')
    )

  df_to_write %>%
    dplyr::select(
      n,
      data,
      item,
      valor,
      categoria,
      obs,
      cidade,
      parcela,
      n_parcelas,
      data_fatura
    ) %>%
    readr::write_csv(filename)

}
